name: Verify

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Build & test linux/amd64 image
      run: make images
      #run: make images test

    - name: Build multi-arch images and binaries
      run: make clean multiarch-tar
